**Dataset 1: Ember China Solar PV Export**

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
# Import Ember Solar PV Export Dataset
data_path = Path("../data/mart_solar_exports_full_release_monthly.csv")

solar_exports = pd.read_csv(data_path)

# Report dataset dimensions
print("Number of rows:", solar_exports.shape[0])
print("Number of columns:", solar_exports.shape[1])

Number of rows: 31254
Number of columns: 13

In [4]:
solar_exports.head()

,Area,Date,Area type,Region,Commodity code,Commodity type,Amount (items),Amount (kg),Amount (USD),Commodity price,Price unit,Capacity (MW),Cumulative capacity (MW)
0,Afghanistan,2017-01-01,Country or economy,Asia,85414020,Panels,49433,333324.0,1663024.0,0.38,USD/W,4.38,4.38
1,Afghanistan,2017-02-01,Country or economy,Asia,85414020,Panels,5452,82456.0,337723.0,0.38,USD/W,0.89,5.27
2,Afghanistan,2017-03-01,Country or economy,Asia,85414020,Panels,51403,940507.0,3477201.0,0.38,USD/W,9.15,14.42
3,Afghanistan,2017-04-01,Country or economy,Asia,85414020,Panels,100875,1306053.0,4783758.0,0.38,USD/W,12.59,27.00
4,Afghanistan,2017-05-01,Country or economy,Asia,85414020,Panels,67325,786843.0,2823671.0,0.38,USD/W,7.43,34.44

In [5]:
solar_exports.info()

<class 'pandas.DataFrame'>
RangeIndex: 31254 entries, 0 to 31253
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Area                      31254 non-null  str
 1   Date                      31254 non-null  str
 2   Area type                 31254 non-null  str
 3   Region                    28391 non-null  str
 4   Commodity code            31254 non-null  int64
 5   Commodity type            31254 non-null  str
 6   Amount (items)            31254 non-null  int64
 7   Amount (kg)               31254 non-null  float64
 8   Amount (USD)              31254 non-null  float64
 9   Commodity price           31254 non-null  float64
 10  Price unit                31254 non-null  str
 11  Capacity (MW)             31254 non-null  float64
 12  Cumulative capacity (MW)  31254 non-null  float64
dtypes: float64(5), int64(2), str(6)
memory usage: 3.1 MB

In [6]:
# Display the first five rows
solar_exports.head()

,Area,Date,Area type,Region,Commodity code,Commodity type,Amount (items),Amount (kg),Amount (USD),Commodity price,Price unit,Capacity (MW),Cumulative capacity (MW)
0,Afghanistan,2017-01-01,Country or economy,Asia,85414020,Panels,49433,333324.0,1663024.0,0.38,USD/W,4.38,4.38
1,Afghanistan,2017-02-01,Country or economy,Asia,85414020,Panels,5452,82456.0,337723.0,0.38,USD/W,0.89,5.27
2,Afghanistan,2017-03-01,Country or economy,Asia,85414020,Panels,51403,940507.0,3477201.0,0.38,USD/W,9.15,14.42
3,Afghanistan,2017-04-01,Country or economy,Asia,85414020,Panels,100875,1306053.0,4783758.0,0.38,USD/W,12.59,27.00
4,Afghanistan,2017-05-01,Country or economy,Asia,85414020,Panels,67325,786843.0,2823671.0,0.38,USD/W,7.43,34.44

In [7]:
# Display column names
solar_exports.columns

Index(['Area', 'Date', 'Area type', 'Region', 'Commodity code',
       'Commodity type', 'Amount (items)', 'Amount (kg)', 'Amount (USD)',
       'Commodity price', 'Price unit', 'Capacity (MW)',
       'Cumulative capacity (MW)'],
      dtype='str')

In [8]:
# Display dataset information
solar_exports.info()

<class 'pandas.DataFrame'>
RangeIndex: 31254 entries, 0 to 31253
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Area                      31254 non-null  str
 1   Date                      31254 non-null  str
 2   Area type                 31254 non-null  str
 3   Region                    28391 non-null  str
 4   Commodity code            31254 non-null  int64
 5   Commodity type            31254 non-null  str
 6   Amount (items)            31254 non-null  int64
 7   Amount (kg)               31254 non-null  float64
 8   Amount (USD)              31254 non-null  float64
 9   Commodity price           31254 non-null  float64
 10  Price unit                31254 non-null  str
 11  Capacity (MW)             31254 non-null  float64
 12  Cumulative capacity (MW)  31254 non-null  float64
dtypes: float64(5), int64(2), str(6)
memory usage: 3.1 MB

In [9]:
# Check temporal coverage
print("Earliest date:", solar_exports["Date"].min())
print("Latest date:", solar_exports["Date"].max())

Earliest date: 2017-01-01
Latest date: 2026-08-01

In [10]:
# Check geographic coverage
print("Number of unique areas:", solar_exports["Area"].nunique())

print("\nRegions:")
print(solar_exports["Region"].value_counts(dropna=False))

Number of unique areas: 244

Regions:
Region
Africa                         7395
Europe                         6471
Asia                           5418
Latin America and Caribbean    4907
NaN                            2863
Middle East                    2178
Oceania                        1619
North America                   403
Name: count, dtype: int64

In [11]:
# Check product categories
print(solar_exports["Commodity type"].value_counts())

print("\nArea types:")
print(solar_exports["Area type"].value_counts())

Commodity type
Panels    21633
Cells      7391
Wafers     2230
Name: count, dtype: int64

Area types:
Area type
Country or economy    28391
Region                 2863
Name: count, dtype: int64

**Dataset 2: IRENA Solar PV Installed Capacity**

In [17]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [20]:
# Import IRENA Solar PV Capacity Dataset
irena_path = Path("../data/IRENA.xlsx")

irena_raw = pd.read_excel(
    irena_path,
    sheet_name="ELEC-C",
    header=None,
    skiprows=2,
    usecols="A:F",
    names=[
        "Country/area",
        "Technology",
        "Data Type",
        "Grid connection",
        "Year",
        "Value"
    ],
    na_values=[".."]
)

irena = irena_raw.loc[irena_raw["Year"].notna()].copy()

In [21]:
## Print Result
print("Number of rows:", irena.shape[0])
print("Number of columns:", irena.shape[1])
irena.head()

Number of rows: 21504
Number of columns: 6

,Country/area,Technology,Data Type,Grid connection,Year,Value
0,Afghanistan,Solar photovoltaic,Electricity Generation (GWh),All,2018.0,38.09
1,NaN,NaN,NaN,NaN,2019.0,57.12
2,NaN,NaN,NaN,NaN,2020.0,64.55
3,NaN,NaN,NaN,NaN,2021.0,76.36
4,NaN,NaN,NaN,NaN,2022.0,89.84

In [22]:
# Display dataset information
irena.info()

<class 'pandas.DataFrame'>
RangeIndex: 21504 entries, 0 to 21503
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country/area     224 non-null    str
 1   Technology       448 non-null    str
 2   Data Type        896 non-null    str
 3   Grid connection  2688 non-null   str
 4   Year             21504 non-null  float64
 5   Value            8921 non-null   float64
dtypes: float64(2), str(4)
memory usage: 1008.1 KB

In [23]:
#temporal coverage
print("Earliest year:", irena["Year"].min())
print("Latest year:", irena["Year"].max())

#technology and data types
print(irena["Technology"].dropna().unique())
print(irena["Data Type"].dropna().unique())

Earliest year: 2018.0
Latest year: 2025.0
<StringArray>
['Solar photovoltaic', 'Solar thermal energy']
Length: 2, dtype: str
<StringArray>
['Electricity Generation (GWh)', 'Electrical Installed Capacity (MW)']
Length: 2, dtype: str